### ISSUE TITLE
Migrar datos a BD producción incluyendo Zamias

### ISSUE THREAD

**Issue by valegrajales** [LBAB-Humboldt/biomodelos_db_api#1]
Como administrador de biomodelos quiero revisar la migración de la base de datos de producción y subir la información de modelos de Zamias para disponer de datos actualizados para la nueva versión y otros servicios.

**Comment by valegrajales** [comment]
Criterio de aceptación: En Biomodelos versión beta deben estar disponibles los datos de producción incluyendo Zamias e información para servicios estadísticos.

**Comment by rickreyjim1** [comment]
Se realizó un dump de la base de datos de producción (se eliminaron 69 especies (colección species), que corresponden a 8805 registros (colección records) y a 55 modelos (en la colección models)), quedando el dump en ../192.168.11.81/BioModelos/marzo8de2017SinTallerBosqueSeco.

Este dump se subió a la base de datos de prueba (192.168.11.81/prueba), corriendo las actualizaciones y validaciones ya descritas. Se incluye en el web service STA2 la salida de source (GET: 192.168.11.81:4000/records/metadata/:taxID, con query source, que entrega el JSON de las fuentes asociadas a dicha especie.
