### ISSUE TITLE
taxID inexistente tumba el servicio API

### ISSUE THREAD

**Issue by rickreyjim1** [LBAB-Humboldt/biomodelos_db_api#10]
Si se realiza una petición con un taxID inexistente (el taxID 1111 no existe en la colección): 
http://192.168.11.81:4000/BioModelos/species/1111 (webservice SPE2)
se produce la caída del servicio, con la siguiente salida de error:

![image](https://cloud.githubusercontent.com/assets/17599971/23721409/a7495996-040f-11e7-8bb8-19df98210d22.png)

**Comment by valegrajales** [comment]
Criterio de aceptación: Al hacer una solicitud con taxID inexistente el API debe retornar error y continuar su funcionamiento normal.
