### ISSUE TITLE
Se muestran campos con contenido diferente.

### ISSUE THREAD

**Issue by rickreyjim1** [LBAB-Humboldt/biomodelos_db_api#11]
Al usar el servicio REC4 (crear registros correspondientes a una especie), se le solicitan 2 campos: adm1 & adm2, pero al mostrar el registro  (servicio web REC1) muestran los campos suggestedStateProvince y suggestedCounty. 

Lo anterior hace que, siempre, cuando se ingrese un registro y luego se proceda a su visualización, dichos campos (en BioModelos, departamento y municipio), serán 'null'.

**Comment by valegrajales** [comment]
The get records service for taxID now returns adm1 and adm2 values
