### ISSUE TITLE
Servicio REST para valores únicos del campo collection según condición

### ISSUE THREAD

**Issue by valegrajales** [LBAB-Humboldt/biomodelos_db_api#12]
Como desarrollador de biomodelos necesito un servicio que me traiga los valores únicos del campo colection para todos los registros de una especie determinada para mostrarlos en la pagina

**Comment by valegrajales** [comment]
Criterio de aceptación: Servicio regresa los valores unicos del campo colection cuando se consulta una especie

**Comment by rbastidas** [comment]
Servicio STA7 creado: "/records/metadata/collection/:taxID"
