### ISSUE TITLE
Existen problemas de validación en el momento de la creación de un nuevo registro por parte de los usuarios

### ISSUE THREAD

**Issue by danflop** [LBAB-Humboldt/biomodelos_db_api#123]

**Comment by uamoreno** [comment]
Se realizó una comparación del documento Json que inicialmente se estaba enviando desde el API, se logró identificar cuales eran los atributos que no cumplían con el esquema de validación de MongoDB, que para el caso de las cadenas, funciona diferente al mongoose, ya que para MongoDB los string no pueden ser null sino que deben ser al menos una cadena vacía así: "".
