### ISSUE TITLE
Conteo correcto de registros para la pestaña información

### ISSUE THREAD

**Issue by valegrajales** [LBAB-Humboldt/biomodelos_db_api#15]
El numero de registros en la pestaña de información no cuenta los registros que no son públicos. Debe contarlos todos.

**Comment by valegrajales** [comment]
Criterio de aceptación: El servicio REST debe retornar el número de registros (incluyendo los no públicos).

**Comment by rbastidas** [comment]
Se borra el campo {"visualizationPrivileges":0} del servicio SPE2
