### ISSUE TITLE
Eliminar colecciones antiguas previa copia de respaldo 

### ISSUE THREAD

**Issue by valegrajales** [LBAB-Humboldt/biomodelos_db_api#19]
Eliminar colecciones antiguas previa copia de respaldo

**Comment by valegrajales** [comment]
Copia de respaldo almacenada en el NAS del venado y colecciones eliminadas de MongoDB Producción.

**Comment by rbastidas** [comment]
Se realiza un Full Backup de la base de datos mongodb (records y produccion). se ejecutaron las siguientes sentencias:

PRODUCCION:
mongodump --host 192.168.11.81 --port 27017 --db produccion -u biomodelos -p "XXXX" --out /home/admin01/Documents/bk_mongodb_20170531_1100_m

RECORDS:
mongodump --host 192.168.11.81 --port 27017 --db records -u biomodelos -p "XXXX" --out /home/admin01/Documents/bk_mongodb_20170531_1100_m

Las copias de respaldo quedan almacenadas en:
\\192.168.205.100\lbab\bk_biomodelos\bk_mongodb\bk_mongodb_20170531_1100_m

La base de datos RECORDS se elimina de MongoDB
