### ISSUE TITLE
Realizar transformación para mapear TaxID v1 a TaxID v2

### ISSUE THREAD

**Issue by valegrajales** [LBAB-Humboldt/biomodelos_db_api#20]
Usar documento generado por Helena en el cual mapea el TaxID Actual en las tres colecciones hacia el TaxID que debería tener dado la identificación de TaxID de BioModelos 1.

**Comment by valegrajales** [comment]
Los indices de la colección producción deben tener el TaxID indicado por Helena

**Comment by rbastidas** [comment]
El cambio de los TaxID se realiza teniendo como base el archivo de .csv
