### ISSUE TITLE
Convertir el campo contributedRecord de la colección records de tipo Boolean a String.

### ISSUE THREAD

**Issue by valegrajales** [LBAB-Humboldt/biomodelos_db_api#27]
Convertir el campo contributedRecord de la colección records de tipo Boolean a String.

**Comment by valegrajales** [comment]
Criterio de aceptación: poner nuevo esquema de base de datos para registros como comentario.

**Comment by rbastidas** [comment]
En el campo "contributedRecord" se encuentran 230256 registros con tipo de dato Boolean y 1793 tipo Null.  Los 230256 tienen un valor de "false". Se ejecuta la siguiente sentencia contra la colección records:
db.getCollection('records').update({"contributedRecord":{$type: 8}}, 
{$set: {"contributedRecord":null}}, {multi:true})
La cual asigna un valor null a los registros que tengan un tipo de dato Boolean en contributedRecord.
El control del tipo de dato para los campos de la colección "records" se realizará por medio del "Document Validation"
