### ISSUE TITLE
API Metadatos de registros

### ISSUE THREAD

**Issue by valegrajales** [LBAB-Humboldt/biomodelos_db_api#3]
Como usuario de biomodelos quiero acceder a los metadatos de registros (fuentes publicas y privadas, instituciones, colectores, colaboradores -son los userid de las personas que han reportado, actualizado o creado- y última actualización) para conocer las fuentes de la información usada y dar reconocimientos a los partipantes del proceso.

**Comment by valegrajales** [comment]
Criterio de aceptación: Servicio API para metadatos de registros retorna los datos solicitados.

**Comment by rbastidas** [comment]
Se realizan 3 consultas para buscar la información del userId_bm que se encuentra anidado en los arreglos de los campos "_reported_", "_created_", "_updated_" de la tabla "records". A continuación se presentan las 3 consultas:

**1. Reported**
db.getCollection('records').aggregate([
{"$match": {"taxID": 86}},
{"$group": {"_id": "$reported.userId_bm", "userId_bm": {"$first": "$reported.userId_bm"}}},
{"$project": {"userId_bm": "$_id", _id: 0}},
{"$unwind": "$userId_bm"},
{"$group": {"_id": "$userId_bm", "userId_bm": {"$first": "$userId_bm"}}},
{"$project": {"userId_bm": "$userId_bm", _id: 0}}
])

**2. Created**
db.getCollection('records').aggregate([
{"$match": {"taxID": 86}},
{"$group": {"_id": "$created.userId_bm", "userId_bm": {"$first": "$created.userId_bm"}}},
{"$project": {"userId_bm": "$_id", _id: 0}},
{"$unwind": "$userId_bm"},
{"$group": {"_id": "$userId_bm", "userId_bm": {"$first": "$userId_bm"}}},
{"$project": {"userId_bm": "$userId_bm", _id: 0}}
])

**3. Updated**
db.getCollection('records').aggregate([
{"$match": {"taxID": 86}},
{"$group": {"_id": "$updated.userId_bm", "userId_bm": {"$first": "$updated.userId_bm"}}},
{"$project": {"userId_bm": "$_id", _id: 0}},
{"$unwind": "$userId_bm"},
{"$group": {"_id": "$userId_bm", "userId_bm": {"$first": "$userId_bm"}}},
{"$project": {"userId_bm": "$userId_bm", _id: 0}}
])

De la misma forma, para acceder a la fecha mas actual de reported, created y updated se realizan 3 consultas:

**1. Reported**
db.getCollection('records').aggregate([
{"$match": {"taxID": 11}},
{"$group": {"_id": "$reported.reportedDate", "reportedDate": {"$max": "$reported.reportedDate"}}},
{"$project": {"reportedDate": "$_id", _id: 0}},
{"$unwind": "$reportedDate"},
{"$group": {"_id": "null", "reportedDateMax": {"$max": "$reportedDate"}}},
{"$project": {"reportedDateMax": "$reportedDateMax", _id: 0}}
])

**2. Updated**
db.getCollection('records').aggregate([
{"$match": {"taxID": 11}},
{"$group": {"_id": "$updated.updatedDate", "updatedDate": {"$max": "$updated.updatedDate"}}},
{"$project": {"updatedDate": "$_id", _id: 0}},
{"$unwind": "$updatedDate"},
{"$group": {"_id": "null", "updatedDateMax": {"$max": "$updatedDate"}}},
{"$project": {"updatedDateMax": "$updatedDateMax", _id: 0}}
])

**3. Created**
db.getCollection('records').aggregate([
{"$match": {"taxID": 11}},
{"$group": {"_id": "$created.createdDate", "createdDate": {"$max": "$created.createdDate"}}},
{"$project": {"createdDate": "$_id", _id: 0}},
{"$unwind": "$createdDate"},
{"$group": {"_id": "null", "createdDateMax": {"$max": "$createdDate"}}},
{"$project": {"createdDateMax": "$createdDateMax", _id: 0}}
])

De lo anterior surge la inquietud de si realizar un query unificado para las consultas en ambos casos desde MongoDB o unir los resultados de las consultas por medio de javaScript.

**Comment by valegrajales** [comment]
Recomendamos concatenar los resultados desde Javascript ya que los datos individuales ya estan generados. Esto es deuda técnica y se calculan 3 puntos de historia.

**Comment by rbastidas** [comment]
Para los servicios "../collaborators/" y "../latest_date/" se siguió la recomendación de generar las consultas individuales en MondoDB y unirlas por medio de JavaScrip en el archivo server.js.
Adicionalmente, se comentariaron todos los "res.json({message:..", que hacían caer el servicio. 
Se implementan los siguientes servicios:
1. "http://192.168.11.81:4000/BioModelos/records/metadata/institutions/:taxID"
2. "http://192.168.11.81:4000/BioModelos/records/metadata/collectors/:taxID"
3. "http://192.168.11.81:4000/BioModelos/records/metadata/sources/:taxID"
4. "http://192.168.11.81:4000/BioModelos/records/metadata/collaborators/:taxID"
5. "http://192.168.11.81:4000/BioModelos/records/metadata/latest_date/:taxID"
