### ISSUE TITLE
Revisar el servicio de adición de nuevo registro para que el campo citation_bm

### ISSUE THREAD

**Issue by valegrajales** [LBAB-Humboldt/biomodelos_db_api#30]
Revisar el servicio de adición de nuevo registro para que el campo citation_bm no sea creado como un campo dentro del documento, sino como un campo dentro del arreglo created. Al parecer el servicio a modificar es REC4

**Comment by valegrajales** [comment]
Criterio de aceptación: Debe pasar la prueba unitaria

**Comment by rbastidas** [comment]
En el API el campo citation_bm se encontraba declarado dos veces:
![image](https://user-images.githubusercontent.com/20953731/27346186-f5d9a45a-55b1-11e7-9ee1-2f34c4d8c113.png)

Se elimina en server.js y en server_development.js

Se prueba mendiante la interfaz de biomodelos beta.
Se chequea en MongoDB:
![image](https://user-images.githubusercontent.com/20953731/27346143-c9ed01ca-55b1-11e7-87e8-69b5ea2d612d.png)
