### ISSUE TITLE
Modificar rutas de archivos png y zip para modelos en desarrollo.

### ISSUE THREAD

**Issue by danflop** [LBAB-Humboldt/biomodelos_db_api#35]
Los campos **png**, **zip** y **thumb** de la colección modelos que contienen la ruta de los archivos, deben guardar solamente el nombre de estos. En el momento los modelos cuyo modelStatus es Developing están almacenando una ruta completa.

**Comment by danflop** [comment]
Los campos png, zip y thumb sólo contienen el nombre del archivo para todos los documentos que se encuentren en la colección Modelos. Se debe probar su funcionamiento en la aplicación.

**Comment by rbastidas** [comment]
Los cambios se realizaron ejecutando la siguientes sentencias:

png:
db.models.update({'$and':[{'modelID':'PRI-1'},{'png':'/models/thresholds/Alouatta_palliata_0_mx.png'}]},
  {$set: {'png': 'Alouatta_palliata_0_mx.png'}}, {multi:true});

thumb:
db.models_copy.update({'$and':[{'modelID':'PRI-1'},{'thumb':'/thumbs/thresholds/Alouatta_palliata_0_mx.png'}]},
  {$set: {'thumb': 'Alouatta_palliata_0_mx.png'}}, {multi:true});

zip:
db.models.update({'$and':[{'modelID':'PRI-1'},{'zip':'/zip/thresholds/Alouatta_palliata_0_mx.zip'}]},
  {$set: {'zip': 'Alouatta_palliata_0_mx.zip'}}, {multi:true});
