### ISSUE TITLE
Incluir nuevos campos en colección y modelo registros

### ISSUE THREAD

**Issue by valegrajales** [LBAB-Humboldt/biomodelos_db_api#38]
Como usuario de BioModelos quisiera que al añadir un registro se ingrese la información de número de catálogo, colección e institución

**Comment by valegrajales** [comment]
Criterio de aceptación: el servicio en API para adicionar registros deberá admitir los nuevos campos.

**Comment by danflop** [comment]
Los campos que guardarán esta información de la colección records son:

- **Número de catálogo:** catalogNumber
- **Colección:** colection
- **Institución:** institution

**Comment by valegrajales** [comment]
Servicio REST Post para crear registros ahora puede recibir los campos con valores: catalogNumber, collection (usar doble l) e institution

**Comment by valegrajales** [comment]
Fixed in dc2d0351abfdafa8d99a75b27020b24e74dc46d5
