### ISSUE TITLE
API metadatos de modelo

### ISSUE THREAD

**Issue by valegrajales** [LBAB-Humboldt/biomodelos_db_api#4]
Como usuario de biomodelos quiero acceder a los metadatos del modelo para conocer las fuentes de la información usada y dar reconocimientos a los participantes del proceso.

**Comment by valegrajales** [comment]
Criterio de aceptación: Servicio API para metadatos de modelo retorna los datos solicitados.

**Comment by rbastidas** [comment]
Se modifica el servicio "/models/metadata/:modelID" agregando el campo "methodFile"
