### ISSUE TITLE
Actualizar diccionario de datos de colección records

### ISSUE THREAD

**Issue by danflop** [LBAB-Humboldt/biomodelos_db_api#48]
Actualizar diccionario de datos de colección records de la base de datos de Mongo.

**Comment by danflop** [comment]
Criterio de aceptación: Archivo con todos los campos que existen en la colección records, tipo de dato, sus definiciones, valores por defecto y posibles valores que puede tomar.

**Comment by danflop** [comment]
El documento debe quedar en formato Markdown para guardarlo en el repositorio de documentación.

**Comment by valegrajales** [comment]
Consultar informe en: http://192.168.205.196/pem/Biomodelos_database/blob/master/mongodb/biomodelos_schema/Schema_biomodelos_records.docx
