### ISSUE TITLE
Servicio API que traiga toda la información de un registro especifico para el ver +

### ISSUE THREAD

**Issue by rbastidas** [LBAB-Humboldt/biomodelos_db_api#56]
Nuevo servicio que retorne toda la información de un registro exceptuando los siguientes campos:
_id
cellID
dbDuplicate
downloadDate
override
resourceFolder
resourceIncorporationDate
resourceName
sourceLayer
spatialDuplicated

**Comment by rbastidas** [comment]
Criterio de aceptación: Servicio que al recibir como parámetro de entrada el _id de un registro retorne todos los campos relacionados con el mismo, exceptuado los listados anteriormente.

**Comment by danflop** [comment]
Hacer visible número de colector y número de colección. @heleolaya
