### ISSUE TITLE
Asociar los registros a los modelos

### ISSUE THREAD

**Issue by rbastidas** [LBAB-Humboldt/biomodelos_db_api#58]
Conformar archivo de excel con los registros que corresponden a cada modelo

**Comment by rbastidas** [comment]
Criterio de aceptación: Archivo de excel o archivo csv con los registros que corresponden a cada modelo que serán insertados en la base de datos.

**Comment by rbastidas** [comment]
@heleolaya Editar archivo de Excel organizado de la siguiente manera: modelID; _ID

**Comment by erikasv** [comment]
Discutir y modificar de acuerdo al estado actual

**Comment by erikasv** [comment]
#59
