### ISSUE TITLE
Migrar Base de datos SQLite a PostgreSQL 

### ISSUE THREAD

**Issue by rbastidas** [LBAB-Humboldt/biomodelos_db_api#64]
Criterio de aceptación: Base de datos relacional migrada a PostgreSQL

**Comment by rbastidas** [comment]
[Biomodelos_test.pdf](https://github.com/LBAB-Humboldt/biomodelos_db_api/files/1647205/Biomodelos_test.pdf)
@danflop

**Comment by danflop** [comment]
@rbastidas El modelo es correcto respecto al esquema de la aplicación.
